on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout
        uses: actions/checkout@v7

      - name: setup pnpm and node
        uses: pnpm/setup@v2
        with:
          version: 11
          runtime: node@26

      - name: install dependencies
        run: pnpm install 

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionLambda
          aws-region: ${{ secrets.AWS_REGION }}

      - name: cdk deploy BackendStack
        run: pnpm exec cdk deploy backend-stack --require-approval never

      - name: cdk deploy ConsoleStack
        run: pnpm exec cdk deploy console-stack --require-approval never
      
      - name: cdk deploy MobileStack
        run: pnpm exec cdk deploy mobile-stack --require-approval neverß